"""VAYU INDEX - Phase 9 anomaly detection.

Phase 9 consumes Phase 8 outputs READ-ONLY and annotates them with anomaly
flags. It never normalizes (Phase 8 owns that), never decides index
eligibility (Phase 10 owns that), and never deletes an observation.
"""

from .rules import (
    ALT_SOURCE_FIRST_FARE_IS_DIAGNOSTIC_ONLY,
    ANOMALY_LEVELS,
    CALIBRATION_DATE,
    CALIBRATION_IS_IN_SAMPLE,
    CALIBRATION_PROTOTYPE,
    CALIBRATION_SOURCE,
    DELETES_OBSERVATIONS,
    EVALUATION_STATUSES,
    FORBIDDEN_OUTPUT_FIELDS,
    INACTIVE_RULES,
    PERFORMS_IMPUTATION,
    PHASE9_SCHEMA_VERSION,
    RULE_IDS,
    RULE_LEVELS,
    RULE_NAMES,
    SEVERITY_ORDER,
    USES_MACHINE_LEARNING,
    USES_RANDOMNESS,
    AnomalyRuleError,
)

__all__ = [
    "ALT_SOURCE_FIRST_FARE_IS_DIAGNOSTIC_ONLY",
    "ANOMALY_LEVELS",
    "AnomalyRuleError",
    "CALIBRATION_DATE",
    "CALIBRATION_IS_IN_SAMPLE",
    "CALIBRATION_PROTOTYPE",
    "CALIBRATION_SOURCE",
    "DELETES_OBSERVATIONS",
    "EVALUATION_STATUSES",
    "FORBIDDEN_OUTPUT_FIELDS",
    "INACTIVE_RULES",
    "PERFORMS_IMPUTATION",
    "PHASE9_SCHEMA_VERSION",
    "RULE_IDS",
    "RULE_LEVELS",
    "RULE_NAMES",
    "SEVERITY_ORDER",
    "USES_MACHINE_LEARNING",
    "USES_RANDOMNESS",
]
